import { supabase } from "./auth";

export type CheckoutItem = {
  product_id: string;
  quantity: number;
  price: number;
  product_name?: string;
  sku?: string | null;
  size_id?: string | null;
  discount?: number;
};

export type CheckoutData = {
  customer_name: string;
  phone: string;
  email?: string;
  address: string;

  subtotal: number;
  shipping: number;
  total: number;

  payment_method: string;
  transaction_id?: string | null;

  shipping_method?: string | null;
  shipping_charge?: number;

  discount?: number;

  /**
   * Clear the customer's cart after successful order creation.
   * Cart checkout: true
   * Buy Now: false
   */
  clear_cart?: boolean;

  items: CheckoutItem[];
};

export async function placeOrder(data: CheckoutData) {
  /*
   * =====================================================
   * 0. CHECK AUTHENTICATION
   * =====================================================
   */

  const {
    data: { user },
    error: userError,
  } = await supabase.auth.getUser();

  if (userError) {
    throw userError;
  }

  if (!user) {
    throw new Error("Please login first.");
  }

  /*
   * =====================================================
   * 0A. BASIC VALIDATION
   * =====================================================
   */

  if (!data.items || data.items.length === 0) {
    throw new Error("Your cart is empty.");
  }

  if (!data.customer_name.trim()) {
    throw new Error("Customer name is required.");
  }

  if (!data.phone.trim()) {
    throw new Error("Phone number is required.");
  }

  if (!data.address.trim()) {
    throw new Error("Delivery address is required.");
  }

  if (!data.payment_method.trim()) {
    throw new Error("Please select a payment method.");
  }

  /*
   * =====================================================
   * 0B. CALCULATE TOTALS
   * =====================================================
   */

  const subtotal = Number(data.subtotal) || 0;
  const shipping = Number(data.shipping) || 0;
  const discount = Number(data.discount) || 0;

  const total =
    Number(data.total) ||
    subtotal + shipping - discount;

  /*
   * =====================================================
   * 1. GENERATE ORDER NUMBER
   * =====================================================
   *
   * IMPORTANT:
   *
   * Order number is now generated by Supabase RPC.
   *
   * We do NOT calculate max order number from the
   * customer's browser anymore.
   *
   * This allows different customers to use the same
   * global order-number sequence even when RLS prevents
   * one customer from reading another customer's orders.
   */

  const {
    data: orderNumber,
    error: orderNumberError,
  } = await supabase.rpc("generate_order_number");

  if (orderNumberError) {
    console.error(
      "Order number generation failed:",
      orderNumberError
    );

    throw orderNumberError;
  }

  if (!orderNumber) {
    throw new Error(
      "Unable to generate order number. Please try again."
    );
  }

  /*
   * =====================================================
   * 2. CREATE ORDER
   * =====================================================
   */

  const {
    data: order,
    error: orderError,
  } = await supabase
    .from("orders")
    .insert({
      order_number: orderNumber,

      user_id: user.id,

      customer_name:
        data.customer_name.trim(),

      phone:
        data.phone.trim(),

      email:
        data.email?.trim() || null,

      address:
        data.address.trim(),

      subtotal,

      shipping,

      total,

      discount,

      status: "Pending",

      payment_status: "Pending",

      payment_method:
        data.payment_method,

      shipping_method:
        data.shipping_method?.trim() ||
        "Standard",

      shipping_charge:
        Number(data.shipping_charge) ||
        shipping,
    })
    .select()
    .single();

  if (orderError || !order) {
    console.error(
      "Order creation failed:",
      orderError
    );

    throw (
      orderError ||
      new Error(
        "Unable to create order. Please try again."
      )
    );
  }

  /*
   * =====================================================
   * 3. CREATE INITIAL ORDER STATUS HISTORY
   * =====================================================
   */

  const {
    error: historyError,
  } = await supabase
    .from("order_status_history")
    .insert({
      order_id: order.id,

      status: "Pending",

      changed_by: user.id,

      note:
        "Order placed by customer. Waiting for admin review.",
    });

  if (historyError) {
    /*
     * Roll back order if status history
     * cannot be created.
     */

    await supabase
      .from("orders")
      .delete()
      .eq("id", order.id)
      .eq("user_id", user.id);

    throw historyError;
  }

  /*
   * =====================================================
   * 4. CREATE ORDER ITEMS
   * =====================================================
   */

  const orderItems = data.items.map((item) => {
    const price =
      Number(item.price) || 0;

    const quantity =
      Number(item.quantity) || 1;

    const discountAmount =
      Number(item.discount) || 0;

    const lineTotal =
      price * quantity -
      discountAmount;

    return {
      order_id: order.id,

      product_id:
        item.product_id,

      product_name:
        item.product_name || null,

      sku:
        item.sku || null,

      size_id:
        item.size_id || null,

      quantity,

      price,

      unit_price:
        price,

      discount:
        discountAmount,

      line_total:
        Math.max(0, lineTotal),
    };
  });

  const {
    error: itemsError,
  } = await supabase
    .from("order_items")
    .insert(orderItems);

  if (itemsError) {
    /*
     * Best-effort cleanup
     */

    await supabase
      .from("orders")
      .delete()
      .eq("id", order.id)
      .eq("user_id", user.id);

    throw itemsError;
  }

  /*
   * =====================================================
   * 5. CREATE INITIAL PAYMENT RECORD
   * =====================================================
   */

  const {
    error: paymentError,
  } = await supabase
    .from("payments")
    .insert({
      order_id:
        order.id,

      user_id:
        user.id,

      payment_method:
        data.payment_method,

      transaction_id:
        data.transaction_id?.trim() ||
        null,

      amount:
        total,

      status:
        "Pending",
    });

  if (paymentError) {
    /*
     * Best-effort cleanup
     */

    await supabase
      .from("order_items")
      .delete()
      .eq("order_id", order.id);

    await supabase
      .from("orders")
      .delete()
      .eq("id", order.id)
      .eq("user_id", user.id);

    throw paymentError;
  }

  /*
   * =====================================================
   * 6. CLEAR CUSTOMER CART
   * =====================================================
   */

  if (data.clear_cart !== false) {
    const {
      error: cartError,
    } = await supabase
      .from("cart_items")
      .delete()
      .eq("user_id", user.id);

    if (cartError) {
      /*
       * Do NOT fail the order if cart clearing fails.
       * Order has already been successfully created.
       */

      console.error(
        "Order created but cart could not be cleared:",
        cartError
      );
    }
  }

  /*
   * =====================================================
   * 7. RETURN ORDER
   * =====================================================
   */

  return order;
}